name: code_editor
description: A code editor and programming learning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
